---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Chata.
--- DateTime: 2019/3/5 19:51
---
local Common=require "app.Common"
local Object=class("Object")

function Object:ctor(node)
    self.sp=cc.Sprite:create()
    self.node=node
    self.node:addChild(self.sp)

    if self.update~=nil then
        self.updateFuncId=cc.Director:getInstance():getScheduler():scheduleScriptFunc(function()
            self:update()
        end,0,false)
    end
end

function Object:alive()
    return self.sp~=nil
end

function Object:getPos()
    return Common.pos2Gird(self.sp:getPositionX(),self.sp:getPositionY())
end

function Object:setPos(x,y)
    local posx,posy=Common.grid2Pos(x,y)
    --print(posx,posy)
    self.sp:setPosition(posx,posy)
    return posx,posy
end

function Object:getRect()
    return Common.newRect(self.sp:getPositionX(),self.sp:getPositionY())
end

function Object:updatePosition(callback)
    local delta=cc.Director:getInstance():getDeltaTime()
    local nextPosX=self.sp:getPositionX()+self.dx*delta
    local nextPosY=self.sp:getPositionY()+self.dy*delta

    if callback(nextPosX,nextPosY) then
        return
    end

    if self.dx~=0 then
        self.sp:setPositionX(nextPosX)
    end
    if self.dy~=0 then
        self.sp:setPositionY(nextPosY)
    end
end

function Object:destory()
    if self.updateFuncId then
        cc.Director:getInstance():getScheduler()
                :unscheduleScriptEntry(self.updateFuncId)
    end

    self.node:removeChild(self.sp)
    self.sp=nil
end

return Object