---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Chata.
--- DateTime: 2019/3/6 1:42
---

local Tank=require "app.Tank"

local PlayerTank=class("PlayerTank",Tank)

function PlayerTank:ctor(node,name,map)
    PlayerTank.super.ctor(self,node,name,map)
    self.dirTable={}
end

function PlayerTank:moveBegin(dir)
    self.dirTable[dir]=socket.gettime()
    self:updateDir()
end

function PlayerTank:moveEnd(dir)
    self.dirTable[dir]=0
    self:updateDir()
end

function PlayerTank:updateDir()
    local maxTime=0
    local maxDir
    for i,j in pairs(self.dirTable) do
        if j>maxTime then
            maxTime=j
            maxDir=i
        end
    end
    self:setDir(maxDir)
end

return PlayerTank