---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Chata.
--- DateTime: 2019/3/5 19:54
---

local Object=require "app.Object"
local SpriteAnimation=require "app.SpriteAnimation"
local Tank=class("Tank",Object)

function Tank:ctor(node,name,map)
    Tank.super.ctor(self,node)
    self.node=node
    self.map=map
    self.dx=0
    self.dy=0
    self.speed=300

    self.dir="up"
    self.spAnim=SpriteAnimation.new(self.sp)
    self.spAnim:define("run",name,8,0.1)
    self.spAnim:setFrame("run",0)
end

function Tank:update()
    self:updatePosition(function (nextPosX,nextPosY)
        local hit
        hit=self.map:collide(nextPosX,nextPosY,-5)
--[[        if hit then
            for i,e in pairs(hit) do
                print(i,e)
            end
        end]]
        return hit
        end)
end

function Tank:setDir(dir)
    if dir==nil then
        self.dx=0
        self.dy=0
        self.spAnim:stop("run")
        return
    elseif dir=="left" then
        self.dx=-self.speed
        self.dy=0
        self.sp:setRotation(-90)
        self.spAnim:play("run")
    elseif dir=="right" then
        self.dx=self.speed
        self.dy=0
        self.sp:setRotation(90)
        self.spAnim:play("run")
    elseif dir=="up" then
        self.dx=0
        self.dy=self.speed
        self.sp:setRotation(0)
        self.spAnim:play("run")
    elseif dir=="down" then
        self.dx=0
        self.dy=-self.speed
        self.sp:setRotation(180)
        self.spAnim:play("run")
    end
end

function Tank:destory()
    self.spAnim:destory()
    Tank.super.destory(self)
end

return Tank